version: "3"

services:
  db:
    image: postgres:latest
    environment:
      POSTGRES_USER: normaliser
      POSTGRES_PASSWORD: normaliser
      POSTGRES_DB: normaliser
    ports:
      - 5432:5432

  adminer:
    image: adminer:latest
    ports:
      - 8080:8080
